- name: 'bug:confirmed'
  color: 'd73a4a'
- name: 'bug:unverified'
  color: 'f9d0c4'
- name: 'chore'
  color: 'ffffff'
- name: 'ci'
  color: '0075ca'
- name: 'dependencies'
  color: '276bd1'
- name: 'documentation'
  color: '0075ca'
- name: 'duplicate'
  color: 'cfd3d7'
- name: 'feature'
  color: 'fcf95a'
- name: 'tests'
  color: 'f06dff'
- name: 'wontfix'
  color: 'ffffff'
