name: Label Sync

on:
  push:
    branches:
      - main
    paths:
      - .github/labels.yml

jobs:
  label-sync:
    name: Label Sync
    runs-on: ubuntu-latest
    if: github.repository_owner == 'maclary'
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Label sync
        uses: crazy-max/ghaction-github-labeler@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
